name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

    deploy:

        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/micro-liberty-351413/app-kukus
        steps:

        - name: Login
          uses: google-github-actions/setup-gcloud@v0
          with:
            project_id: 'micro-liberty-351413'
            service_account_email: 'fauzna-syawalino@micro-liberty-351413.iam.gserviceaccount.com'
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME

        - name: Test Docker image
          run: docker run $IMAGE_NAME sh -c "node index.js"

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run: gcloud run deploy micro-liberty-351413 --image $IMAGE_NAME --region us-central1 --platform managed